// <auto-generated />
using System;
using Merlin.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Merlin.Backend.Migrations
{
    [DbContext(typeof(MerlinDbContext))]
    [Migration("20260622215842_AddMemoryLifecycleFields")]
    partial class AddMemoryLifecycleFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.AssistantTurnEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTextSoFar")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterruptedByUserMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterruptionReason")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUserMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenTextSoFar")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("State");

                    b.HasIndex("TopicId");

                    b.ToTable("assistant_turns", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEdgeEntity", b =>
                {
                    b.Property<string>("FromConceptId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToConceptId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("FromConceptId", "ToConceptId", "RelationType");

                    b.HasIndex("RelationType");

                    b.HasIndex("ToConceptId");

                    b.ToTable("concept_edges", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentConceptId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptType");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentConceptId");

                    b.ToTable("concepts", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveTopic")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationTopicEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("conversation_topics", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.MemoryConceptEntity", b =>
                {
                    b.Property<string>("MemoryId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("MemoryId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("memory_concepts", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.MemoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactContent")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Importance")
                        .HasColumnType("REAL");

                    b.Property<string>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryAnchorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedIntoMemoryId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceConversationId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTurnId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersedesMemoryId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UserConfirmed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Importance");

                    b.HasIndex("MemoryType");

                    b.HasIndex("Project");

                    b.HasIndex("SourceConversationId");

                    b.HasIndex("SourceTurnId");

                    b.HasIndex("Status");

                    b.HasIndex("Topic");

                    b.HasIndex("Status", "MemoryType");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.PromptCompilationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompiledBlocksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompiledPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncludedConceptIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludedMemoryIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludedProfileFactIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("TurnId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PromptType");

                    b.HasIndex("TurnId");

                    b.ToTable("prompt_compilations", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.UserProfileFactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMemoryId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersedesFactId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ProfileId", "Key")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("ProfileId", "Key", "Status");

                    b.ToTable("user_profile_facts", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.AssistantTurnEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationEntity", "Conversation")
                        .WithMany("AssistantTurns")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationTopicEntity", "Topic")
                        .WithMany("AssistantTurns")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEdgeEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", "FromConcept")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", "ToConcept")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromConcept");

                    b.Navigation("ToConcept");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", "ParentConcept")
                        .WithMany("ChildConcepts")
                        .HasForeignKey("ParentConceptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentConcept");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationTopicEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationEntity", "Conversation")
                        .WithMany("Topics")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.MemoryConceptEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", "Concept")
                        .WithMany("MemoryConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.MemoryEntity", "Memory")
                        .WithMany("MemoryConcepts")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.PromptCompilationEntity", b =>
                {
                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationEntity", "Conversation")
                        .WithMany("PromptCompilations")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merlin.Backend.Infrastructure.Persistence.Entities.AssistantTurnEntity", "Turn")
                        .WithMany("PromptCompilations")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.AssistantTurnEntity", b =>
                {
                    b.Navigation("PromptCompilations");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConceptEntity", b =>
                {
                    b.Navigation("ChildConcepts");

                    b.Navigation("IncomingEdges");

                    b.Navigation("MemoryConcepts");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationEntity", b =>
                {
                    b.Navigation("AssistantTurns");

                    b.Navigation("PromptCompilations");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.ConversationTopicEntity", b =>
                {
                    b.Navigation("AssistantTurns");
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.Persistence.Entities.MemoryEntity", b =>
                {
                    b.Navigation("MemoryConcepts");
                });
#pragma warning restore 612, 618
        }
    }
}
