// <auto-generated />
using System;
using Merlin.Backend.Infrastructure.TrustedRegistry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Merlin.Backend.Infrastructure.TrustedRegistry.Migrations
{
    [DbContext(typeof(TrustedRegistryDbContext))]
    [Migration("20260623072005_InitialTrustedRegistry")]
    partial class InitialTrustedRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Merlin.Backend.Infrastructure.TrustedRegistry.Entities.TrustedAppMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("NormalizedAlias")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("Status");

                    b.HasIndex("UseCount");

                    b.HasIndex("Status", "NormalizedAlias");

                    b.ToTable("trusted_app_mappings", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.TrustedRegistry.Entities.TrustedCommandMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedOriginalCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Intent");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("NormalizedOriginalCommand")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("Status");

                    b.HasIndex("ToolName");

                    b.HasIndex("UseCount");

                    b.HasIndex("Status", "NormalizedOriginalCommand");

                    b.ToTable("trusted_command_mappings", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.TrustedRegistry.Entities.TrustedRegistryEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("EventType");

                    b.ToTable("trusted_registry_events", (string)null);
                });

            modelBuilder.Entity("Merlin.Backend.Infrastructure.TrustedRegistry.Entities.TrustedUrlMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("NormalizedAlias")
                        .IsUnique()
                        .HasFilter("Status = 'active'");

                    b.HasIndex("Status");

                    b.HasIndex("Url");

                    b.HasIndex("UseCount");

                    b.HasIndex("Status", "NormalizedAlias");

                    b.ToTable("trusted_url_mappings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
